// <auto-generated />
namespace MVC_Pratice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class correctStudentTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(correctStudentTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202508091436584_correctStudentTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
